### register
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "name": "vangiang",
    "phone" : "0976320547",
    "password": "123456",
    "role": "USER"
}

### signin
POST http://localhost:5000/api/auth/signin
Content-Type: application/json

{
    "phone" : "01472583487",
    "password": "123456"
}